### PR TITLE
Check environment and run FreeSurferEnv.sh if necessary

### PR DESCRIPTION
**Pull request by effigies**
Addresses #102.

Check `os.environ` and run `$FREESURFER_HOME/FreeSurferEnv.sh` if not the most recent script to edit the `PATH`. Parse the resulting environment and pass to `mri_vol2surf`, avoiding modifying the base process environment.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. I assume you've tried it and it works?

**Comment by effigies** [comment]
Yes, run through all new paths.

**Comment by effigies** [comment]
Though, it would mistake a manual `PATH="$FREESURFER/bin:$PATH"` for having previously run `FreeSurferEnv.sh`. If that's a problem, I could use a different check.

**Comment by Eric89GXL** [comment]
I think that's an okay corner case to address later if need be

**Comment by agramfort** [comment]
if this works I am happy

**Comment by mwaskom** [comment]
This won't work on windows, but I am guessing that is not an issue because this whole function won't work on windows anyway?

**Comment by effigies** [comment]
That was my assumption.

**Comment by Eric89GXL** [comment]
Thanks @effigies!

**Pull request merged**
