### PR TITLE
ENH: Add doc build

### PR DESCRIPTION
**Pull request by Eric89GXL**
This should fix AppVeyor and make it build the docs (in noplot mode).

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I'll merge this once the CIs are happy since it fixes AppVeyor

**Comment by christianbrodbeck** [comment]
Is reverting the mlab backend necessary to get the tests to work? It will make the tests less complete...

**Comment by Eric89GXL** [comment]
They cause AppVeyor to crash

**Comment by christianbrodbeck** [comment]
I see... could we make it system-dependent?

**Comment by Eric89GXL** [comment]
... they also cause windows to open locally during testing, which is less than ideal. The best thing would be to make Mayavi more fully support the `test` backend.

But I agree it's slightly better to cover more fully, so I'll make a commit to triage for Windows.

**Comment by christianbrodbeck** [comment]
Yeah I agree windows opening during testing are less than ideal...  at least as it is now you can change to the `test` backend temporarily with one change.

**Comment by Eric89GXL** [comment]
Okay we're green so I'll squash and merge. But if people feel like looking feel free and we can iterate.

**Pull request merged**
