### PR TITLE
DOC changes

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Re #165, updating changes. `setup.py` already has Python 3 classifiers. Is #139 substantial enough to include a note?

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
@mwaskom, are these okay? Anything else I can do?

**Comment by Eric89GXL** [comment]
LGTM +1 for merge

**Comment by agramfort** [comment]
thx @christianbrodbeck

**Comment by mwaskom** [comment]
Sorry, been, uh, distracted the past couple of days. Thanks for doing this. I'll try to get a release out, but any of the other developers should feel free to as well if they have time.

**Comment by agramfort** [comment]
release done !

**Comment by christianbrodbeck** [comment]
Great! Thanks @agramfort !

**Pull request merged**
