### PR TITLE
FIX Brain.set_data_time_index():  skip data without time axis

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Fix for a corner case where multiple data layers are added, and not all of them have a time axis

### CODE REVIEW

**Comment by mwaskom** [comment]
Ah I think I've hit this before and couldn't figure out why. Thanks!

**Comment by mwaskom** [comment]
Does anyone know why our travis builds are taking forever to get going lately?

**Comment by Eric89GXL** [comment]
No idea. It has been slower to run but not to start on other repos

**Comment by mwaskom** [comment]
Is this travis failure related to these changes?

**Comment by christianbrodbeck** [comment]
Very unlikely it's form these changes because the relevant test (`test_image `) never adds a data-layer. Also could not spot any changed version in the installed packages. I can't rerun the build to see whether it fails consistently, can one of you?

**Comment by mwaskom** [comment]
Kicking it to see what happens...

**Comment by christianbrodbeck** [comment]
all clear...

**Pull request merged**
