### PR TITLE
Compatibility updates

### PR DESCRIPTION
**Pull request by christianbrodbeck**
This is needed to get PySurfer to import in an environment with Python 3.10 and nibabel 5.1.

### CODE REVIEW

**Comment by larsoner** [comment]
MNE-Python no longer uses PySurfer and I don't have the bandwidth to maintain this package. Maybe I could add you as a maintainer @christianbrodbeck ?

**Comment by christianbrodbeck** [comment]
Sure!

**Comment by larsoner** [comment]
Done!

**Comment by christianbrodbeck** [comment]
@Timothy-Anders0n I added that, too, thanks for pointing it out

@larsoner okay to merge this without another review? And how would we go about making a minor release?

**Comment by larsoner** [comment]
Yes you can maintain in whatever way you see fit. Personally I would try to fix CIs then rely on green but that could be a lot of work.

I probably have PyPI credentials to add you so you could upload a sdist and wheel. Let me know your PyPI username if it's different from GitHub

**Comment by larsoner** [comment]
I think I found you on PyPI, invitation sent

**Pull request merged**
