### PR TITLE
Allow brain without x offset

### PR DESCRIPTION
**Pull request by aestrivex**
The automatic offset creates a problem with my program which uses the vertex coordinates for a complicated algorithm to snap subcortical locations to optimally selected surface vertices and then plots the results. Easiest fix is to allow the user to disable this feature.

### CODE REVIEW

**Comment by mwaskom** [comment]
I think I'd prefer this as `offset=True` rather than `disable_offset=False`, do others have thoughts?

**Comment by aestrivex** [comment]
Doesn't matter to me, I implemented the change.

**Comment by Eric89GXL** [comment]
LGTM

**Comment by mwaskom** [comment]
Same here, thanks!

**Pull request merged**
