### PR TITLE
MRG: Always force GUI updates

### PR DESCRIPTION
**Pull request by larsoner**
@nfoti can you see if this fixes your problem?

This forces a GUI process loop update when calling `_force_render`, which is useful e.g. to deal with the toolbar removal at the beginning. @nfoti found that getting the model-view matrix in a script was different before/after allowing the interpreter to idle, which is a sign that the idle-GUI-loop code was doing something to the display, which shouldn't happen if no interaction has taken place and we are properly forcing rendering changes.

Tests pass locally, let's see if the CIs are happy.

### CODE REVIEW

**Comment by larsoner** [comment]
Examples still look okay:

https://16-1551431-gh.circle-artifacts.com/0/tmp/circle-artifacts.dQ84wpM/html/auto_examples/index.html

**Comment by nfoti** [comment]
@larsoner This fixed my problem.

Thanks.

**Comment by larsoner** [comment]
Great, ready for review/merge from my end, then

**Comment by agramfort** [comment]
thx @larsoner

**Pull request merged**
