### PR TITLE
MRG, FIX: Remove force render

### PR DESCRIPTION
**Pull request by larsoner**
Over at MNE [we have been getting failures](https://github.com/mne-tools/mne-python/pull/7294) that seem to be triggered by the GUI stuff we do when `__del__` is called. This hopefully avoids the problem.

WIP until we can do some runs in MNE to see if it makes the problem go away.

### CODE REVIEW

**Comment by larsoner** [comment]
Added Azure as a CI while I was at it

**Comment by larsoner** [comment]
Same failures occur in MNE, but I still think this is worth having since the `_force_render` does not seem to be required here

**Comment by larsoner** [comment]
@mwaskom feel free to review/merge if you're happy

**Comment by mwaskom** [comment]
Thanks!

**Pull request merged**
